"""Load MITRE ATT&CK data for coverage mapping.

Two modes are supported:

* **Bundled compact DB** (``data/attack_db.json``) — generated by
  :mod:`attack_mapper.build_db` from the official MITRE CTI STIX bundle. This
  is the default because it is small (``~180 KB``) and needs no network.
* **Full STIX bundle** (``enterprise-attack.json``) — if you point
  ``ATTACK_MAPPER_STIX`` at the raw STIX 2.0/2.1 bundle, it is parsed directly
  so you always have the latest techniques/tactics.
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass, field
from typing import Dict, List, Optional

DEFAULT_DB_PATH = os.path.join(os.path.dirname(__file__), "data", "attack_db.json")


@dataclass
class AttackDB:
    """In-memory view of ATT&CK tactics and techniques."""

    version: str = ""
    tactics: Dict[str, dict] = field(default_factory=dict)
    techniques: Dict[str, dict] = field(default_factory=dict)

    def technique_name(self, tid: str) -> Optional[str]:
        t = self.techniques.get(tid.upper())
        return t["name"] if t else None

    def tactic_name(self, shortname: str) -> Optional[str]:
        t = self.tactics.get(shortname)
        return t["name"] if t else shortname

    def valid_technique(self, tid: str) -> bool:
        return tid.upper() in self.techniques

    def resolve_tactic_token(self, token: str) -> str:
        """Map a TA tactic ID (e.g. ``TA0002``) to its shortname.

        Returns the token unchanged if it isn't a known TA id, so scope
        tokens can be technique IDs, shortnames, or TA ids interchangeably.
        Older compact DBs may lack the ``id`` field — fall back to parsing
        the TA id out of the tactic URL.
        """
        wanted = token.strip().upper()
        if not wanted.startswith("TA"):
            return token
        for shortname, tac in self.tactics.items():
            taid = tac.get("id")
            if not taid:
                url = tac.get("url") or ""
                if "/tactics/" in url:
                    taid = url.rstrip("/").rsplit("/", 1)[-1]
            if taid and taid.upper() == wanted:
                return shortname
        return token


def _load_compact(path: str) -> AttackDB:
    with open(path, "r", encoding="utf-8") as fh:
        d = json.load(fh)
    return AttackDB(
        version=d.get("version", ""),
        tactics=d.get("tactics", {}),
        techniques=d.get("techniques", {}),
    )


def _load_stix(path: str) -> AttackDB:
    with open(path, "r", encoding="utf-8") as fh:
        bundle = json.load(fh)
    tactics: Dict[str, dict] = {}
    techniques: Dict[str, dict] = {}
    version = ""
    for o in bundle.get("objects", []):
        t = o.get("type")
        # Revoked/deprecated objects are kept in the STIX bundle for history,
        # but they are no longer part of ATT&CK — including them would inflate
        # the coverage denominator with techniques that don't exist anymore.
        if o.get("revoked") or o.get("x_mitre_deprecated"):
            continue
        if t == "x-mitre-matrix":
            # The bundle has no version object; the matrix name + last-modified
            # date is the most honest snapshot identifier available.
            modified = (o.get("modified") or "")[:10]
            version = f'{o.get("name", "ATT&CK")} ({modified})' if modified else o.get("name", "")
        elif t == "x-mitre-tactic":
            sn = o.get("x_mitre_shortname")
            ref = next(
                (e for e in o.get("external_references", []) if e.get("source_name") == "mitre-attack"),
                {},
            )
            tactics[sn] = {
                "id": ref.get("external_id"),
                "name": o.get("name"),
                "shortname": sn,
                "url": ref.get("url"),
            }
        elif t == "attack-pattern":
            refs = [e for e in o.get("external_references", []) if e.get("source_name") == "mitre-attack"]
            if not refs:
                continue
            ext = refs[0].get("external_id")
            if not (ext and ext.startswith("T")):
                continue
            techniques[ext] = {
                "id": ext,
                "name": o.get("name"),
                "url": refs[0].get("url"),
                "tactics": [p.get("phase_name") for p in o.get("kill_chain_phases", [])],
                "is_subtechnique": "." in ext,
            }
    return AttackDB(version=version or "stix", tactics=tactics, techniques=techniques)


def load_attack(db_path: Optional[str] = None) -> AttackDB:
    """Load ATT&CK data.

    Resolution order:
    1. ``db_path`` argument if provided.
    2. ``ATTACK_MAPPER_STIX`` env var -> full STIX bundle.
    3. ``ATTACK_MAPPER_DB`` env var -> compact DB.
    4. Bundled compact DB shipped with the package.
    """
    stix = os.environ.get("ATTACK_MAPPER_STIX")
    compact = db_path or os.environ.get("ATTACK_MAPPER_DB") or os.path.abspath(DEFAULT_DB_PATH)

    if stix and os.path.isfile(stix):
        return _load_stix(stix)
    if os.path.isfile(compact):
        return _load_compact(compact)
    raise FileNotFoundError(
        f"No ATT&CK database found. Looked for compact DB at {compact} "
        f"and STIX at {stix}. Run `python -m attack_mapper.build_db` to generate one."
    )
